import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Mired",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className="text-black">
          <header>
            <Header />
          </header>
          <main className="min-h-screen ">
            {children}
          </main>
          <footer>
              <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
